name: Testing Framework

on:
  workflow_dispatch

jobs:
  compose-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run docker-compose
        run: docker compose up -d

      - name: Wait and test backend
        run: |
          sleep 10

      - name: run python test
        run: python main.py

      - name: Tear down
        run: docker compose down

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            report.txt
    
